name: clean

on:
  push:
    branches:
      - main
env:
  PROJECT_VERSION: 1.0.0
  MAVEN_OPTS: "-Dmaven.repo.local=${{github.workspace}}/.m2/repository"

jobs:    
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java Jdk
        uses: actions/setup-java@v5.0.0
        with:
          java-version : 17
          distribution: zulu

      - name : Cache
        uses: actions/cache@v4.3.0
        with:
          path: ${{github.workspace}}/.m2/repository
          key: cache-dependances

      - name: build package with Maven
        run: mvn clean package -DskipTests -X

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: helloworld-${{env.PROJECT_VERSION}}.jar
          path: target/helloworld-1.0-SNAPSHOT.jar
         
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    #continue-on-error: true -> positionné ici, ça empêche l'execution des étapes du job mais permet aux autres jobs de s'executer
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java Jdk
        uses: actions/setup-java@v5.0.0
        with:
          java-version : 17
          distribution: zulu

      - name : Cache
        uses: actions/cache@v4.3.0
        with:
          path: ${{github.workspace}}/.m2/repository
          key: cache-dependances

      - name: build package with Maven
        run: mvn test
        continue-on-error: true # -> positionné ici, ça permet l'execution des autres étapes du job après l'erreur et permet aux autres jobs de s'executer

  deploy:
      name: Deploy App
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v6.0.0
          with:
             name: helloworld-${{env.PROJECT_VERSION}}.jar
        - name: Deploy to Server
          run: echo "Deploying application..."
