name: clean

on:
  push:
    branches:
      - main
env:
  PROJECT_VERSION: 1.0.0
  MAVEN_OPTS: "-Dmaven.repo.local=~/dependances"
  
jobs:    
  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0
      - name: Setup Java Jdk
        uses: actions/setup-java@v5.0.0
        with:
          java-version : 17
          distribution: zulu

      - name : cache
        run: "sudo mkdir ~/dependances"

      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          path: "~/dependances"
          key: "key"

      - name: build package
        run: mvn clean package -DskipTests ${MAVEN_OPTS}
