name: Test de workflow

on :
  #schedule:
   # - cron: "0 * * * *"
  workflow_dispatch:
  
jobs:
  nomExemple:
    runs-on: ubuntu-latest
    steps:
      - name : Display checkout source code
        run: echo "Récupération du code source"

      - name: Display and end checkout source code
        run: echo "Fin récupération du code source"
      
